BrandwatchLtd/bwapi

lib/bwapi/client/admin.rb, lib/bwapi/client/admin/demographics.rb
Added the /admin/demographics/classify endpoint
```
Ran rubocop and rspec
Tested locally
```
=> NoTask - Added demographics classify endpoint

lib/bwapi/client/brandwatch.rb, lib/bwapi/client/brandwatch/log_level.rb, lib/bwapi/client/brandwatch/usage_report.rb, lib/bwapi/client/command_center/displays/scenes.rb, lib/bwapi/client/projects.rb, lib/bwapi/client/projects/query/mentionfind.rb, lib/bwapi/client/projects/signals/groups.rb, lib/bwapi/error.rb
***Changes***
Added 4 new endpoints
```
GET /projects/#{project_id}/signals/groups/#{group_id}/signals
GET /brandwatch/usageReport/client/#{clientId}/start/#{startDate}/end/#{endDate}
GET /projects/#{project_id}/query/#{query_id}/mentionfind
POST /brandwatch/log-level
```
***Rubocop***
111 files inspected, no offenses detected
***Rspec***
Finished in 0.02681 seconds (files took 1.68 seconds to load)
41 examples, 0 failures
[Coveralls] Outside the Travis environment, not sending data.
Coverage report generated for RSpec to /Users/lee/brandwatch/bwapi/coverage. 987 / 1354 LOC (72.9%) covered.
=> QA-752 - Added 4 new endpoints

lib/bwapi/client/brandwatch/clients.rb, lib/bwapi/client/brandwatch/clients/command_center.rb, lib/bwapi/client/brandwatch/clients/command_center/limits.rb, lib/bwapi/client/brandwatch/clients/command_center/scene_types.rb, lib/bwapi/client/brandwatch/clients/command_center/themes.rb, lib/bwapi/client/brandwatch/clients/command_center/users.rb, lib/bwapi/client/brandwatch/clients/command_center/users/access.rb, lib/bwapi/client/brandwatch/command_center.rb, lib/bwapi/client/brandwatch/command_center/scene_types.rb, lib/bwapi/client/brandwatch/command_center/themes.rb, lib/bwapi/client/command_center.rb, lib/bwapi/client/command_center/category_colours.rb, lib/bwapi/client/command_center/colour_palette.rb, lib/bwapi/client/command_center/display_access.rb, lib/bwapi/client/command_center/display_access/users.rb, lib/bwapi/client/command_center/display_access/users/access.rb, lib/bwapi/client/command_center/projects.rb, lib/bwapi/client/command_center/projects/category_colours.rb, lib/bwapi/client/command_center/projects/data.rb, lib/bwapi/client/command_center/projects/tag_colours.rb, lib/bwapi/client/command_center/query_colours.rb, lib/bwapi/client/command_center/scene_types.rb, lib/bwapi/client/command_center/tag_colours.rb
Added endpoints for /commandcenter
Added /brandwatch command center endpoints
Minor updates of comment typos etc
Ran rubocop and rspec
=> QA-2167 - Added the missing command center endpoints

lib/bwapi/client/user.rb, lib/bwapi/client/user/instagram_credentials.rb
I added Instragram API2 endpoint for BWAPI wrapper. 
I ran tests results looks like:
Finished in 0.02279 seconds (files took 0.56066 seconds to load)
41 examples, 0 failures
=> NoTask - Added /user/instagramcredentials endpoints

lib/bwapi/client/command_center/projects/category_colours.rb, lib/bwapi/client/command_center/projects/tag_colours.rb
Added options to tagColours and categoryColours endpoints that where missing the 'opts' parameter
Ran rubocop and rspec
=> NoTask - Added options to categoryColour and tagColour endpoints

lib/bwapi/client/admin/clients/users/sharing.rb, lib/bwapi/client/command_center/query_colours.rb, lib/bwapi/version.rb, spec/bwapi/configuration_spec.rb, spec/bwapi/default_spec.rb
- Fixed typo in /admin/clients/{client_id}/users/{user_id}/sharing endpoints
- Fixed VERB typo in /admin/clients/{client_id}/users/{user_id}/sharing endpoints
- Added opts for PUT /commandcenter/queryColours/{query_id} endpoint
- Upped version to 11.0.1 for pre release
- Updated RSpec tests with new version
Ran Rubocop and RSpec
Tested locally
```
6 scenarios (6 passed)
23 steps (23 passed)
0m19.507s
```
=> NoTask Fixing a typo and added a missing opts

lib/bwapi/client/brandwatch.rb, lib/bwapi/client/brandwatch/ditto_brands.rb, lib/bwapi/client/projects.rb, lib/bwapi/client/projects/ditto_queries.rb
* Added the ditto endpoints to the bwapi gem - these may change so please do not merge until I'm happy for these to be added.
* Ran the unit and rubocop tests as per the contributing guidelines.
```
115 files inspected, no offenses detected
Finished in 0.06423 seconds (files took 0.98803 seconds to load)
140 examples, 0 failures
```
=> NoTask - new ditto endpoints

lib/bwapi/client/brandwatch/price_structures.rb, lib/bwapi/client/brandwatch/price_structures/clients.rb
- Added /brandwatch/pricestructures/clients/{clientId} endpoint
- Ran rubocop
- Ran rspec
=> QA-2458 Added brandwatch client price structures endpoint

lib/bwapi/client/brandwatch/clients/users.rb
- Added GET /brandwatch/clients/{client_id}/users endpoint
- Added GET /brandwatch/clients/{client_id}/users/{user_id} endpoint
- Added PUT /brandwatch/clients/{client_id}/users/{user_id} endpoint
=> Added brandwatch client users endpoints

lib/bwapi/client/admin/reseller.rb
- Added missing options for `reseller_mention_usage_report` method
```
140 examples, 0 failures
147 files inspected, no offenses detected
```
=> Added missing options for reseller_mention_usage_report method

lib/bwapi/client/user/twitter_credentials.rb
***Changes***
Added the options and parameters to the twitterCredentials.   This was needed as part of automating the /user/twittercredentials endpoint
***Tests***
cucumber -p integration features/api/user/twitter_credentials/twitter_credentials.feature
3 scenarios (3 passed)
13 steps (13 passed)
0m3.858s
=> QA-685 - Added opts to twitter_credentials

lib/bwapi/client/admin/clients.rb
Adding a new endpoint that retrieves the client usage per month
rubocop:
146 files inspected, no offenses detected
rspec:
Finished in 0.0612 seconds (files took 2.22 seconds to load)
140 examples, 0 failures
=> ENT-1048: Add client usage endpoint

lib/bwapi/client/admin/reseller.rb
This PR will add the new endpoint for returning the reseller clients usage report
RUBOCOP:
146 files inspected, no offenses detected
pry(main)> bw.reseller_client_mention_usage_report(47,{month:'2015-05-01'})
=> {"reportMonth"=>"2015-05-01T00:00:00.000+0000",
"clientId"=>47,
"reportLines"=>
[{"clientId"=>47,
"clientName"=>"CL2",
"projectId"=>78,
"projectName"=>"cl1",
"queryId"=>172,
"queryName"=>"abc",
"pricingPackage"=>"Vitor_pricing",
"queriesAllowed"=>60,
"mentionsAllowed"=>600,
"mentionVolumeForMonth"=>641,
"queryStartDate"=>"2015-05-07",
"queryEndDate"=>nil,
"daysInMonth"=>31,
"daysActiveInMonth"=>25}],
"clientName"=>"CL2"}
=> ENT-940_Adding_the_clients_usage_report_endpoint

lib/bwapi/client/projects.rb, lib/bwapi/client/projects/alerts.rb
There are endpoint for Alerts
Results for Rubocop:
`134 files inspected, no offenses detected`
and for rspec:
`Finished in 0.05699 seconds (files took 2.23 seconds to load)`
=> NRP-3051-Alert endpoints added

lib/bwapi/client/admin.rb, lib/bwapi/client/admin/client.rb
This PR will add the GET /admin/client/{clientId}/usagebyquery endpoint
Rubocop:
148 files inspected, no offenses detected
=> ENT-940 Adding usage by query endpoint

lib/bwapi/client/admin.rb, lib/bwapi/client/admin/pricing_upgrades.rb
This PR will add the endpoint for GET /admin/pricingupgrades/{clientId} which will be used to test the upgrade clients feature on /Administration
Rubocop
149 files inspected, no offenses detected
=> ENT-939_Add_pricing_upgrades_enpoint

lib/bwapi/client/admin.rb, lib/bwapi/client/admin/projects.rb
This PR will add the new endpoint which allows users to lock/unlock queries.
Rubocop:
148 files inspected, no offenses detected
[5] pry(main)>bw.unlock_query(457,352)
=> {"id"=>352,
"name"=>"1010",
"description"=>"",
"creationDate"=>"2015-06-26T15:37:50.233+0000",
"lastModificationDate"=>"2015-07-13T09:17:06.597+0000",
"industry"=>"general-(recommended)",
"includedTerms"=>["1010"],
"excludedTerms"=>[],
"contextTerms"=>[],
"languages"=>["en"],
"averageMonthlyMentions"=>278,
"twitterLimit"=>1500,
"dailyLimit"=>10000,
"type"=>"search string",
"twitterScreenName"=>nil,
"highlightTerms"=>["1010"],
"links"=>
{"lastSevenDaysSentiment"=>"http://bond:8880/projects/457/data/volume/queries/sentiment.json?access_token=18eaf2b2-49fd-4029-8f58-b0bfbc6428af&queryId=352&startDate=2015-07-08T13:33:16.121Z& …
=> ENT-1554 Add lock queries endpoint

lib/bwapi/client/client.rb
This PR will just add a new endpoint to return all the subclients of a client (GET /client/subclients).
rubocop:
151 files inspected, no offenses detected
TEST:
pry(main)> bw.client_subclients
=> {"resultsTotal"=>-1,
"resultsPage"=>-1,
"resultsPageSize"=>-1,
"results"=>
[{"id"=>45,
"name"=>"CL1",
"parentId"=>44,
"startDate"=>"2015-03-19T00:00:00.000+0000",
"expiryDate"=>nil,
"website"=>"",
"address1"=>"",
"address2"=>"",
"address3"=>"",
"country"=>"",
"postcode"=>"",
"contactName"=>"",
"contactEmail"=>"vitor+c@brandwatch.com",
"contactTitle"=>"",
"contactTelephone"=>"",
"contactMobile"=>"",
"mentionArchiveSize"=>240,
"tags"=>{"ratelimit.limit"=>"30", "ratelimit.period"=>"10", "resellerTermsAndConditionsAccepted"=>"true", "resellerTermsAndConditionsAcceptedBy"=>"1372", …
=> ENT-1477: Adding client_subclients endpoint

lib/bwapi/client.rb, spec/bwapi/client_spec.rb
There is now a super admin api user that behaves like an api user but has a short life like and application user
`151 files inspected, no offenses detected`
`142 examples, 0 failures`
=> NoTask Added api super admin client check method

lib/bwapi/client/admin.rb, lib/bwapi/client/client.rb, lib/bwapi/client/client/pricing_options.rb
***Changes***
Updated the repo to reflect the move of the pricing options endpoint from `admin` to `client`
=> NoTask - move pricing options endpoint

lib/bwapi/version.rb, spec/bwapi/configuration_spec.rb, spec/bwapi/default_spec.rb
***changes***
Bumped the version to `12.0.0`
=> NoTask - Bump Major version

CHANGELOG.md
***Changes***
Added list of changes for next major version
=> NoTask - Updated changelog ready for new gem build

lib/bwapi/client/projects.rb
New endpoint for copy project.
=> NoTask- Endpoint for project copy

.travis.yml, lib/bwapi/client/brandwatch/usage_report.rb, lib/bwapi/client/projects/queries.rb
I added post method for new query wizard.
=> NRP-3606-Added endpoint for query wizard post

.travis.yml, lib/bwapi/client/oauth.rb, lib/bwapi/default.rb, lib/bwapi/response/error.rb, lib/bwapi/response/performance.rb, lib/bwapi/version.rb, spec/bwapi/configuration_spec.rb
Updated .travis.yml so that bundler is updated on each test run.
=> Updated .travis.yml

lib/bwapi/client/projects.rb, lib/bwapi/client/projects/instagram_queries.rb
=> QA-3560_API_IG_channel

lib/bwapi/client/brandwatch.rb, lib/bwapi/client/brandwatch/users.rb
Added a missing endpoint - `Brandwatch/users/details` 
***Rubocop***
153 files inspected, no offenses detected
=> QA-4728 - Added the BW/Users/Details endpoint

lib/bwapi/client/projects/preview_search.rb
There a endpoint which do not have test coverage and need to be added to provide confident coverage for test search.
=> NoTask-Added new search endpoints

lib/bwapi/client/brandwatch/clients.rb, lib/bwapi/client/brandwatch/clients/login.rb
***Changes***
This PR adds a login module to the bwapi repo which will allow the login report endpoint to be tested.
This is blocking my other work on this scenario so I need this to be merged soon.
https://office.brandwatch.com/jira/browse/RR-757
No features changed in this repo so I assume no need to add test results to this.
=> Creating login module file for login report scenario - RR-757

lib/bwapi/version.rb
***Changes***
Following on from my previous PR in this repo, I need to bump the version.
Previous one:
https://github.com/BrandwatchLtd/bwapi/pull/233
Related to:
https://office.brandwatch.com/jira/browse/RR-757
=> Version bump of bwapi

.rubocop.yml, Gemfile, bwapi.gemspec, lib/bwapi.rb, lib/bwapi/client.rb, lib/bwapi/client/oauth.rb, lib/bwapi/response/error.rb, lib/bwapi/version.rb, spec/bwapi/configuration_spec.rb, spec/bwapi/default_spec.rb, spec/helper.rb
The Jenkins tests were giving a false positive because of coveralls.
I have removed coveralls, fixed some rake and rubocop issues.
- Removed coveralls
- Updated rubocop to require at minimum 0.38
- Updated gemspec to include at least rake 12.0
- Fixed some minor rubocop issues
- Bumped to version 13.2.0 as there are no breaking changes to the functionality here
=> Remove coveralls

lib/bwapi/client/admin.rb, lib/bwapi/client/projects.rb, lib/bwapi/client/projects/facebook_channels.rb, lib/bwapi/configuration.rb, lib/bwapi/version.rb, spec/bwapi/request_spec.rb
Needed for https://github.com/BrandwatchLtd/qa-brandwatch-api/pull/133
=> FAC-215: Add facebook channels module for new endpoint

lib/bwapi/client/projects/facebook_channels.rb, lib/bwapi/version.rb
=> FAC-215: Add missing pagination params for fb channels

.rubocop.yml, lib/bwapi/client.rb, lib/bwapi/client/pricing.rb, lib/bwapi/client/projects.rb, lib/bwapi/client/projects/instagram_queries.rb, lib/bwapi/client/projects/twitter_queries.rb, lib/bwapi/client/projects/usage_summary.rb, lib/bwapi/version.rb
Added new endpoints into repo.
=> No task request update
